name: auto_release

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
      canary:
        required: true
        type: boolean

jobs:
  run:
    if: ${{ !github.event.pull_request.draft }}

    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Fetch tags
        run: git fetch --unshallow --tags

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Npm cache
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.commit_hash }}
          path: ./

      - if: ${{ inputs.canary == true }}
        name: Do canary release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_CHANNEL }}
        run: |
          npx auto canary

      - if: ${{ inputs.canary == false }}
        name: Ship release
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE_CHANNEL }}
        run: |
          npx auto shipit
