name: Bump Version on Push

on:
  workflow_call:
    inputs:
      commit_hash:
        required: true
        type: string
      canary:
        required: false
        type: boolean
        default: false
      build:
        required: false
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}

      - name: Set Git user
        run: |
          git config user.name "SparkHireBot"
          git config user.email "dev@sparkhire.com"

      - name: Setup Node 20.x
        uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          node-version: 20.x

      - name: Npm cache
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-cache-node-modules-${{ hashFiles('**/package-lock.json') }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install npm dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: npm ci

      - name: Get merged branch name
        id: get-head-branch-name
        run: |
          echo "Merged branch name: ${{ github.event.pull_request.head.ref }}"
          echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT

      - name: Fail if branch_name not set
        if: ${{ steps.get-head-branch-name.outputs.branch_name == '' }}
        run: |
          echo "Branch name was not set" >&2
          exit 1

      - name: Get package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Fail if current-version not set
        if: ${{ steps.package-version.outputs.current-version == '' }}
        run: |
          echo "Current version was not set!" >&2
          exit 1

      - name: Get package name
        id: package-name
        run: |
          PACKAGE_NAME=$(npm pkg get name)
          TRIMMED_PACKAGE_NAME=$(echo "$PACKAGE_NAME" | sed 's/"//g')
          echo "package_name=$TRIMMED_PACKAGE_NAME" >> $GITHUB_OUTPUT

      - name: Determine version bump
        id: determine-version-bump
        run: |
          echo "Current version: ${{ steps.package-version.outputs.current-version }}"
          echo "Branch name: ${{ steps.get-head-branch-name.outputs.branch_name }}"

          BRANCH_NAME="${{ steps.get-head-branch-name.outputs.branch_name }}"
          CURRENT_VERSION="${{ steps.package-version.outputs.current-version }}"

          if [[ "$BRANCH_NAME" == *"release/"* ]]; then
            echo "This is a release branch. Setting version bump to 'major'."
            VERSION_BUMP="major"
          elif [[ "$BRANCH_NAME" == *"major/"* ]]; then
            echo "This is a major branch. Setting version bump to 'major'."
            VERSION_BUMP="major"
          elif [[ "$BRANCH_NAME" == *"minor/"* ]]; then
            echo "This is a minor branch. Setting version bump to 'minor'."
            VERSION_BUMP="minor"
          elif [[ "$BRANCH_NAME" == *"patch/"* ]]; then
            echo "This is a patch branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          elif [[ "$BRANCH_NAME" == *"hotfix/"* ]]; then
            echo "This is a hotfix branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          elif [[ "$BRANCH_NAME" == *"feature/"* ]]; then
            echo "This is a feature branch. Setting version bump to 'minor'."
            VERSION_BUMP="minor"
          elif [[ "$BRANCH_NAME" == *"bugfix/"* ]]; then
            echo "This is a bugfix branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          elif [[ "$BRANCH_NAME" == *"chore/"* ]]; then
            echo "This is a chore branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          elif [[ "$BRANCH_NAME" == *"docs/"* ]]; then
            echo "This is a docs branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          elif [[ "$BRANCH_NAME" == *"test/"* ]]; then
            echo "This is a test branch. Setting version bump to 'patch'."
            VERSION_BUMP="patch"
          else
            echo "Branch name does not match any known patterns. Defaulting version bump to 'patch'."
            VERSION_BUMP="patch"
          fi

          echo "Determined version bump: $VERSION_BUMP"

          echo "version_bump=$VERSION_BUMP" >> $GITHUB_OUTPUT

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build-${{ inputs.commit_hash }}
          path: ./

      - name: Echo version bump
        run: |
          echo "Version bump type: ${{ steps.determine-version-bump.outputs.version_bump }}"

      - name: Bump version
        id: bump-version
        run: |
          PUBLISHED_VERSION=$(npm version ${{ inputs.canary && 'pre' || '' }}${{ steps.determine-version-bump.outputs.version_bump }} ${{ inputs.canary && '--preid=canary-' || '' }}${{ inputs.canary && inputs.commit_hash || '' }} -m "Bump version to %s [skip ci]")
          echo $PUBLISHED_VERSION
          echo "published_version=$PUBLISHED_VERSION" >> $GITHUB_OUTPUT

      - name: Generate install cmd
        id: generate-install-cmd
        run: |
          INSTALL_CMD="npm install ${{ steps.package-name.outputs.package_name}}@${{ steps.bump-version.outputs.published_version }}"
          echo $INSTALL_CMD
          echo "install_cmd=$INSTALL_CMD" >> $GITHUB_OUTPUT

      # - name: Publish package
      #   id: publish-package
      #   run: |
      #     npm publish ${{ inputs.build && '' || '--ignore-scripts' }} --tag ${{ inputs.canary && 'canary' || 'latest' }}
      #   env:
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_PUBLISH }}

      # - name: Push changes
      #   if: ${{ inputs.canary == false }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ steps.generate-token.outputs.token }}
      #     branch: ${{ github.ref }}

      - name: Update PR Description
        uses: nefrob/pr-description@v1.2.0
        with:
            content: "\n\n<!-- published package install -->\n```\n# Install package cmd\n${{ steps.generate-install-cmd.outputs.install_cmd }}```\n<!-- end published package install -->"
            regex: "\n\n<!-- published package install -->.*?<!-- end published package install -->"
            regexFlags: ims
            token: ${{ secrets.GITHUB_TOKEN }}
